### ISSUE TITLE
URGENT - Since v2.5.7 all SSL being auto-renewed (even onetime orders)

### ISSUE THREAD

**Issue by qhgh** [gogetssl/whmcs-addon#178]
Hi,

Since v2.5.7 all SSL have been invoiced for renewal, we do not use auto-renew, we only use onetime.

![ssl-1-time](https://user-images.githubusercontent.com/43718405/110297877-d1de9700-7feb-11eb-97e5-2d10523ee4fe.png)

1 customer alone has over 300 invoices now for past SSL that are expired not needing renewal.

Please can you help urgently? 

Thanks,
C

**Comment by vlad-evg** [comment]
Checking...

**Comment by vlad-evg** [comment]
That should fix the problem. 
https://github.com/gogetssl/whmcs-addon/releases/tag/v2.5.8

Modules Garden stated: 
"I checked it, the logs show that the invoices were generated by WHMCS not by the module. However, the module may have an influence on this because after the last changes, the date of the next invoice for the certificate was unnecessarily updated by cron. "
