### ISSUE TITLE
"Payment Pending" invoices redirect user to clientarea.php

### ISSUE THREAD

**Issue by DennisSkov** [gogetssl/whmcs-addon#218]
**Describe the bug**
When the module generates a new "Payment pending" invoice, the user is redirected to the client area homepage upon clicking "Pay now" on the invoice.

**To Reproduce**
1. Have the module generate a new renewal invoice automatically
2. Make sure the invoice has "Payment pending" status
3. Log in as the client
4. Access the invoice
5. Click "Pay now"

**Expected behavior**
It should be possible for the client to pay the invoice

I don't know what the purpose of the "Payment pending" status is. Why isn't status just set to "Unpaid"?

**Comment by vlad-evg** [comment]
We will check that shortly

**Comment by vlad-evg** [comment]
Please try that version
https://my.gogetssl.com/gogetssl-2.7.8_beta.zip

Comments from developers:
"t seems to me that I have solved this issue and now the payment for the invoice should proceed correctly.

As for the status, you just wanted renew invoices to have a different status than Unpaid so that they would not be automatically counted by WHMCS as overdue, only optional to pay."

**Comment by DennisSkov** [comment]
Thank you, that solved the issue.

Could you make a setting to allow us to generate invoices as "Unpaid"?

**Comment by vlad-evg** [comment]
Please check that:

https://github.com/gogetssl/whmcs-addon/releases/tag/v2.7.9
