### ISSUE TITLE
How to clear up old SSL set status to Completed? 

### ISSUE THREAD

**Issue by qhgh** [gogetssl/whmcs-addon#247]
Hi there,

We have many SSLs in an 'Active' state in WHMCS when the SSL setup was never completed etc. and has since expired.

Here is an example: 

Registration Date: 02/01/2019 (its now 2023)
Billing Cycle: One Time	
SSLCenter API Order ID	xxx
Cron Synchronized	2023-09-24
Comodo Order ID	xxx
Configuration Status	Completed
Domain	x.x.co.uk
Order Status	Rejected
Approver email	admin@x.co.uk
Order Status Description	Awaiting Validation (Full)

Is there a way to clean these up and set them as Completed? There are too many to do manually. 

Thanks for any ideas. 
C.

**Comment by vlad-evg** [comment]
Hey!

So to make them Completed, I guess we have to determinate the rule when it should happen. You want to change orders to Completed if Order status Rejected?

**Comment by vlad-evg** [comment]
Another moment, you are saying "We have many SSLs in an 'Active' state in WHMCS when the SSL setup was never completed etc. and has since expired.", if SSL setup was never completed there will be no Approver email etc... Even in your example you state "Configuration Status Completed"... 

So please clarify what exactly you are trying to do? :) more looks like it is all about Rejected orders
