### ISSUE TITLE
No email with cert configuration

### ISSUE THREAD

**Issue by hexcom** [gogetssl/whmcs-addon#94]
1) After purchase there is no email with configuration link (tested with PositiveSSL and Trial). Earlier versions don't have this bug (version 2.2.8). 

2) There is no info in domain filed about domain name for which cert has been generated - it's only visible in cert details. So it's difficult to find right cert on client level. Of course such info was visible in earlier versions.

and one more thing: quality of your addon. I didn't see such low code quality. With each version one thing is fixed and three other stop working. I work with many modules and such buggy addon i see first in my life..

**Comment by vlad-evg** [comment]
Dear Hexcom,

1. 2.2.8 is the latest released version. 2.3.0 is a pre-release and has issues
https://www.screencast.com/t/HaO7kjaR

2. Again, 2.3.0 is a pre-release, please switch back to 2.2.8

About the quality, well, yes, we selected one of the most popular developers (https://www.modulesgarden.com/) who process and create many different plugins. Due to large amount of issues we did a huge QA test recently, next release should include many fixes and be stable :/ if you have any suggestions about module developers, please share

**Comment by vlad-evg** [comment]
+ if you have any good suggestions on how to improve the module we would more then happy to listen to them and implement them.

**Comment by hexcom** [comment]
I wrote about issues with 2.2.8, i dont use 2.3.0.

**Comment by hexcom** [comment]
Why this issue has been closed? It's not solved!

**Comment by vlad-evg** [comment]
Next release has fix for that. I will keep case open until released. Sorry
